apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajit
  namespace: aditya
  labels:
    app: aditya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ajit
  template:
    metadata:
      labels:
        app: ajit
    spec:
      containers:
      - name: ajit
        image: adityaji.azurecr.io/ajit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
